export const catchingConfig = {
  neighbourhoodRadius: 32,
  fishAttentionMinDistance: 12,
  fishAttentionMaxDistance: 52,
  fishAttentionAngleDegrees: 42,
  fishBitePollIntervalMs: 100,
  noBiteHintDelayMs: 8500,
  hookDebugRadius: 20,
  biteFishSwimDurationMs: 1550,
  biteFishTurnDurationMs: 800,
  biteFishFadeInDurationMs: 450,
  biteFishShakeDurationMs: 800,
  biteFishShakeRotationDegrees: 3,
  biteFishShakeCycles: 3,
  fishForwardAngleOffset: -90,
  fishMouthOffsetScale: 0.42,
  minBiteFishSwimDistanceScale: 1.15,
  clusterBiteMinDelayMs: 1000,
  clusterBiteMaxDelayMs: 3500,
  clusterBiteJitterMin: 0.85,
  clusterBiteJitterMax: 1.2,
  neighbourhoodBiteMinDelayMs: 3000,
  neighbourhoodBiteMaxDelayMs: 6000,
  neighbourhoodBiteJitterMin: 0.9,
  neighbourhoodBiteJitterMax: 1.35,
  neighbourhoodFishSize: 22,
}
